[package]
name = "fitparser"
version = "0.1.0"
authors = ["Matthew Stadelman <stadelmanma@gmail.com>"]
edition = "2018"

[build-dependencies]
calamine = "0.16.1"

[dependencies]
chrono = "0.4"
nom = "5"
