[package]
name = "fitparser"
version = "0.1.0"
authors = ["Matthew Stadelman <stadelmanma@gmail.com>"]
edition = "2018"

[build-dependencies]
calamine = "0.16.1"

[dependencies]
chrono = {version = "0.4", features = ["serde"] }
nom = "5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
